language: node_js
node_js:
  - 18
services:
    - docker
install:
    - echo "nothing needs to be"
before_script:
    - echo "no tests"
script:
    - docker --version
    - docker build -t test-travis .
    - docker tag test-travis namnguyen1997/test-travis:latest
ater_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push namnguyen1997/test-travis